//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServicio.AreasService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TriangleDTO", Namespace="http://schemas.datacontract.org/2004/07/WebServiceApp.DTO")]
    [System.SerializableAttribute()]
    public partial class TriangleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PerimeterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SideAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SideBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SideCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Perimeter {
            get {
                return this.PerimeterField;
            }
            set {
                if ((this.PerimeterField.Equals(value) != true)) {
                    this.PerimeterField = value;
                    this.RaisePropertyChanged("Perimeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SideA {
            get {
                return this.SideAField;
            }
            set {
                if ((this.SideAField.Equals(value) != true)) {
                    this.SideAField = value;
                    this.RaisePropertyChanged("SideA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SideB {
            get {
                return this.SideBField;
            }
            set {
                if ((this.SideBField.Equals(value) != true)) {
                    this.SideBField = value;
                    this.RaisePropertyChanged("SideB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SideC {
            get {
                return this.SideCField;
            }
            set {
                if ((this.SideCField.Equals(value) != true)) {
                    this.SideCField = value;
                    this.RaisePropertyChanged("SideC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SquareDTO", Namespace="http://schemas.datacontract.org/2004/07/WebServiceApp.DTO")]
    [System.SerializableAttribute()]
    public partial class SquareDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PerimeterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SideField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Perimeter {
            get {
                return this.PerimeterField;
            }
            set {
                if ((this.PerimeterField.Equals(value) != true)) {
                    this.PerimeterField = value;
                    this.RaisePropertyChanged("Perimeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Side {
            get {
                return this.SideField;
            }
            set {
                if ((this.SideField.Equals(value) != true)) {
                    this.SideField = value;
                    this.RaisePropertyChanged("Side");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RingDTO", Namespace="http://schemas.datacontract.org/2004/07/WebServiceApp.DTO")]
    [System.SerializableAttribute()]
    public partial class RingDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PerimeterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RadiusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Perimeter {
            get {
                return this.PerimeterField;
            }
            set {
                if ((this.PerimeterField.Equals(value) != true)) {
                    this.PerimeterField = value;
                    this.RaisePropertyChanged("Perimeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Radius {
            get {
                return this.RadiusField;
            }
            set {
                if ((this.RadiusField.Equals(value) != true)) {
                    this.RadiusField = value;
                    this.RaisePropertyChanged("Radius");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RectangleDTO", Namespace="http://schemas.datacontract.org/2004/07/WebServiceApp.DTO")]
    [System.SerializableAttribute()]
    public partial class RectangleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PerimeterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Perimeter {
            get {
                return this.PerimeterField;
            }
            set {
                if ((this.PerimeterField.Equals(value) != true)) {
                    this.PerimeterField = value;
                    this.RaisePropertyChanged("Perimeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Triangle", Namespace="http://schemas.datacontract.org/2004/07/WebServiceApp.Models")]
    [System.SerializableAttribute()]
    public partial class Triangle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PerimeterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SideAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SideBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SideCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Perimeter {
            get {
                return this.PerimeterField;
            }
            set {
                if ((this.PerimeterField.Equals(value) != true)) {
                    this.PerimeterField = value;
                    this.RaisePropertyChanged("Perimeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SideA {
            get {
                return this.SideAField;
            }
            set {
                if ((this.SideAField.Equals(value) != true)) {
                    this.SideAField = value;
                    this.RaisePropertyChanged("SideA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SideB {
            get {
                return this.SideBField;
            }
            set {
                if ((this.SideBField.Equals(value) != true)) {
                    this.SideBField = value;
                    this.RaisePropertyChanged("SideB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SideC {
            get {
                return this.SideCField;
            }
            set {
                if ((this.SideCField.Equals(value) != true)) {
                    this.SideCField = value;
                    this.RaisePropertyChanged("SideC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Square", Namespace="http://schemas.datacontract.org/2004/07/WebServiceApp.Models")]
    [System.SerializableAttribute()]
    public partial class Square : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PerimeterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SideField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Perimeter {
            get {
                return this.PerimeterField;
            }
            set {
                if ((this.PerimeterField.Equals(value) != true)) {
                    this.PerimeterField = value;
                    this.RaisePropertyChanged("Perimeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Side {
            get {
                return this.SideField;
            }
            set {
                if ((this.SideField.Equals(value) != true)) {
                    this.SideField = value;
                    this.RaisePropertyChanged("Side");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ring", Namespace="http://schemas.datacontract.org/2004/07/WebServiceApp.Models")]
    [System.SerializableAttribute()]
    public partial class Ring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PerimeterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RadiusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Perimeter {
            get {
                return this.PerimeterField;
            }
            set {
                if ((this.PerimeterField.Equals(value) != true)) {
                    this.PerimeterField = value;
                    this.RaisePropertyChanged("Perimeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Radius {
            get {
                return this.RadiusField;
            }
            set {
                if ((this.RadiusField.Equals(value) != true)) {
                    this.RadiusField = value;
                    this.RaisePropertyChanged("Radius");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rectangle", Namespace="http://schemas.datacontract.org/2004/07/WebServiceApp.Models")]
    [System.SerializableAttribute()]
    public partial class Rectangle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PerimeterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Perimeter {
            get {
                return this.PerimeterField;
            }
            set {
                if ((this.PerimeterField.Equals(value) != true)) {
                    this.PerimeterField = value;
                    this.RaisePropertyChanged("Perimeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AreasService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListTriangles", ReplyAction="http://tempuri.org/IService1/ListTrianglesResponse")]
        ClienteServicio.AreasService.TriangleDTO[] ListTriangles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListTriangles", ReplyAction="http://tempuri.org/IService1/ListTrianglesResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.TriangleDTO[]> ListTrianglesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListSquares", ReplyAction="http://tempuri.org/IService1/ListSquaresResponse")]
        ClienteServicio.AreasService.SquareDTO[] ListSquares();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListSquares", ReplyAction="http://tempuri.org/IService1/ListSquaresResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.SquareDTO[]> ListSquaresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListRings", ReplyAction="http://tempuri.org/IService1/ListRingsResponse")]
        ClienteServicio.AreasService.RingDTO[] ListRings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListRings", ReplyAction="http://tempuri.org/IService1/ListRingsResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.RingDTO[]> ListRingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListRectangles", ReplyAction="http://tempuri.org/IService1/ListRectanglesResponse")]
        ClienteServicio.AreasService.RectangleDTO[] ListRectangles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListRectangles", ReplyAction="http://tempuri.org/IService1/ListRectanglesResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.RectangleDTO[]> ListRectanglesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTriangle", ReplyAction="http://tempuri.org/IService1/CreateTriangleResponse")]
        ClienteServicio.AreasService.Triangle CreateTriangle(ClienteServicio.AreasService.TriangleDTO Triangle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTriangle", ReplyAction="http://tempuri.org/IService1/CreateTriangleResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.Triangle> CreateTriangleAsync(ClienteServicio.AreasService.TriangleDTO Triangle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateSquare", ReplyAction="http://tempuri.org/IService1/CreateSquareResponse")]
        ClienteServicio.AreasService.Square CreateSquare(ClienteServicio.AreasService.SquareDTO Square);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateSquare", ReplyAction="http://tempuri.org/IService1/CreateSquareResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.Square> CreateSquareAsync(ClienteServicio.AreasService.SquareDTO Square);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateRing", ReplyAction="http://tempuri.org/IService1/CreateRingResponse")]
        ClienteServicio.AreasService.Ring CreateRing(ClienteServicio.AreasService.RingDTO Ring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateRing", ReplyAction="http://tempuri.org/IService1/CreateRingResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.Ring> CreateRingAsync(ClienteServicio.AreasService.RingDTO Ring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateRectangle", ReplyAction="http://tempuri.org/IService1/CreateRectangleResponse")]
        ClienteServicio.AreasService.Rectangle CreateRectangle(ClienteServicio.AreasService.RectangleDTO Rectangle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateRectangle", ReplyAction="http://tempuri.org/IService1/CreateRectangleResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.Rectangle> CreateRectangleAsync(ClienteServicio.AreasService.RectangleDTO Rectangle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTriangleById", ReplyAction="http://tempuri.org/IService1/GetTriangleByIdResponse")]
        ClienteServicio.AreasService.TriangleDTO GetTriangleById(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTriangleById", ReplyAction="http://tempuri.org/IService1/GetTriangleByIdResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.TriangleDTO> GetTriangleByIdAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSquareById", ReplyAction="http://tempuri.org/IService1/GetSquareByIdResponse")]
        ClienteServicio.AreasService.SquareDTO GetSquareById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSquareById", ReplyAction="http://tempuri.org/IService1/GetSquareByIdResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.SquareDTO> GetSquareByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRingById", ReplyAction="http://tempuri.org/IService1/GetRingByIdResponse")]
        ClienteServicio.AreasService.RingDTO GetRingById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRingById", ReplyAction="http://tempuri.org/IService1/GetRingByIdResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.RingDTO> GetRingByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRectangleById", ReplyAction="http://tempuri.org/IService1/GetRectangleByIdResponse")]
        ClienteServicio.AreasService.RectangleDTO GetRectangleById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRectangleById", ReplyAction="http://tempuri.org/IService1/GetRectangleByIdResponse")]
        System.Threading.Tasks.Task<ClienteServicio.AreasService.RectangleDTO> GetRectangleByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClienteServicio.AreasService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClienteServicio.AreasService.IService1>, ClienteServicio.AreasService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteServicio.AreasService.TriangleDTO[] ListTriangles() {
            return base.Channel.ListTriangles();
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.TriangleDTO[]> ListTrianglesAsync() {
            return base.Channel.ListTrianglesAsync();
        }
        
        public ClienteServicio.AreasService.SquareDTO[] ListSquares() {
            return base.Channel.ListSquares();
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.SquareDTO[]> ListSquaresAsync() {
            return base.Channel.ListSquaresAsync();
        }
        
        public ClienteServicio.AreasService.RingDTO[] ListRings() {
            return base.Channel.ListRings();
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.RingDTO[]> ListRingsAsync() {
            return base.Channel.ListRingsAsync();
        }
        
        public ClienteServicio.AreasService.RectangleDTO[] ListRectangles() {
            return base.Channel.ListRectangles();
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.RectangleDTO[]> ListRectanglesAsync() {
            return base.Channel.ListRectanglesAsync();
        }
        
        public ClienteServicio.AreasService.Triangle CreateTriangle(ClienteServicio.AreasService.TriangleDTO Triangle) {
            return base.Channel.CreateTriangle(Triangle);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.Triangle> CreateTriangleAsync(ClienteServicio.AreasService.TriangleDTO Triangle) {
            return base.Channel.CreateTriangleAsync(Triangle);
        }
        
        public ClienteServicio.AreasService.Square CreateSquare(ClienteServicio.AreasService.SquareDTO Square) {
            return base.Channel.CreateSquare(Square);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.Square> CreateSquareAsync(ClienteServicio.AreasService.SquareDTO Square) {
            return base.Channel.CreateSquareAsync(Square);
        }
        
        public ClienteServicio.AreasService.Ring CreateRing(ClienteServicio.AreasService.RingDTO Ring) {
            return base.Channel.CreateRing(Ring);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.Ring> CreateRingAsync(ClienteServicio.AreasService.RingDTO Ring) {
            return base.Channel.CreateRingAsync(Ring);
        }
        
        public ClienteServicio.AreasService.Rectangle CreateRectangle(ClienteServicio.AreasService.RectangleDTO Rectangle) {
            return base.Channel.CreateRectangle(Rectangle);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.Rectangle> CreateRectangleAsync(ClienteServicio.AreasService.RectangleDTO Rectangle) {
            return base.Channel.CreateRectangleAsync(Rectangle);
        }
        
        public ClienteServicio.AreasService.TriangleDTO GetTriangleById(int ID) {
            return base.Channel.GetTriangleById(ID);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.TriangleDTO> GetTriangleByIdAsync(int ID) {
            return base.Channel.GetTriangleByIdAsync(ID);
        }
        
        public ClienteServicio.AreasService.SquareDTO GetSquareById(int Id) {
            return base.Channel.GetSquareById(Id);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.SquareDTO> GetSquareByIdAsync(int Id) {
            return base.Channel.GetSquareByIdAsync(Id);
        }
        
        public ClienteServicio.AreasService.RingDTO GetRingById(int Id) {
            return base.Channel.GetRingById(Id);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.RingDTO> GetRingByIdAsync(int Id) {
            return base.Channel.GetRingByIdAsync(Id);
        }
        
        public ClienteServicio.AreasService.RectangleDTO GetRectangleById(int Id) {
            return base.Channel.GetRectangleById(Id);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.AreasService.RectangleDTO> GetRectangleByIdAsync(int Id) {
            return base.Channel.GetRectangleByIdAsync(Id);
        }
    }
}
